function notebook_function4 = pendulum_equation4(t,x1,x2,x3,x4)
%PENDULUM_EQUATION4
%    NOTEBOOK_FUNCTION4 = PENDULUM_EQUATION4(T,X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    13-Nov-2013 12:58:27

t2 = sin(x3);
t3 = cos(x3);
notebook_function4 = (t2.*4.56876e3-t2.*t3.*7.8529e1+t3.*x2.*2.8e1)./(t2.^2.*7.8529e1+5.9e1);
