function notebook_function = pendulum_equation(t,x1,x2)
%PENDULUM_EQUATION
%    NOTEBOOK_FUNCTION = PENDULUM_EQUATION(T,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    08-Nov-2013 07:02:49

notebook_function = sin(x1).*-3.322033898305085e1;
