function notebook_function3 = pendulum_equation3(t,x1)
%PENDULUM_EQUATION3
%    NOTEBOOK_FUNCTION3 = PENDULUM_EQUATION3(T,X1)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    08-Nov-2013 10:38:37

notebook_function3 = -x1+3.1416;
