function notebook_function = pendulum_equation(t,x1,x2)
%PENDULUM_EQUATION
%    NOTEBOOK_FUNCTION = PENDULUM_EQUATION(T,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    08-Nov-2013 09:49:46

notebook_function = x1.*-2.0e1-x2.*1.051840721262209e-1+sin(x1).*3.322033898305085e1+6.2832e1;
