function notebook_function2 = pendulum_equation2(t,x1,x2,x3)
%PENDULUM_EQUATION2
%    NOTEBOOK_FUNCTION2 = PENDULUM_EQUATION2(T,X1,X2,X3)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    08-Nov-2013 10:38:37

notebook_function2 = x1.*-1.001-x2.*1.051840721262209e-1+x3.*1.0e-1+sin(x1).*3.322033898305085e1+3.1447416;
