function notebook_function = pendulum_equation(t,x1,x2)
%PENDULUM_EQUATION
%    NOTEBOOK_FUNCTION = PENDULUM_EQUATION(T,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    02-Nov-2013 20:15:07

notebook_function = -x2-sin(x1).*1.96e1;
