function notebook_functionA = pendulum_equation_A
%PENDULUM_EQUATION_A
%    NOTEBOOK_FUNCTIONA = PENDULUM_EQUATION_A

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    13-Nov-2013 17:45:08

notebook_functionA = reshape([0.0,0.0,0.0,0.0,1.0,-1.4e-1,0.0,4.745762711864407e-1,0.0,-1.30438e1,0.0,7.6105610169e1,0.0,0.0,1.0,0.0],[4, 4]);
