function notebook_functionB = pendulum_equation_B
%PENDULUM_EQUATION_B
%    NOTEBOOK_FUNCTIONB = PENDULUM_EQUATION_B

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    13-Nov-2013 17:45:08

notebook_functionB = [0.0;5.0e-3;0.0;-1.694915254237288e-2];
