function notebook_function5 = pendulum_equation5(t,x1,x2,x3,x4,x5,u)
%PENDULUM_EQUATION5
%    NOTEBOOK_FUNCTION5 = PENDULUM_EQUATION5(T,X1,X2,X3,X4,X5,U)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    13-Nov-2013 17:45:08

notebook_function5 = -x3;
